# Dockerfile.API
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY src ./src
COPY data ./data
RUN dotnet restore

# Copy everything else and build
COPY . ./
WORKDIR /app/src/ArticlesCrawler.PublicApi
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/src/ArticlesCrawler.PublicApi/out .
ENTRYPOINT ["dotnet", "API.dll"]