version: '3.8'
services:
  vnexpress-crawler:
    build: 
      context: .
      dockerfile: Dockerfile.VNExpressCrawler
    volumes:
      - db-data:/app/data
  tuoitre-crawler:
    build: 
      context: .
      dockerfile: Dockerfile.TuoiTreCrawler
    volumes:
      - db-data:/app/data
  api:
    build: 
      context: .
      dockerfile: Dockerfile.PublicApi
    volumes:
      - db-data:/app/data
    ports:
      - "5000:5000"
    logging:
      driver: json-file
volumes:
  db-data: